version: "3"
services:
  listingspage:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
    depends_on:
      - postgres  # Make sure to start this service after the postgres service

  postgres:
    image: postgres:latest
    container_name: MyDatabase
    environment:
      POSTGRES_USER: "jg"
      POSTGRES_PASSWORD: "03asd3wsada"
      POSTGRES_DB: "listings"
    ports:
      - "5432:5432"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d