version: '3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: "jg"
      POSTGRES_PASSWORD: "03asd3wsada"
      POSTGRES_DB: "listings"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend 


 
