INSERT INTO Listings (ListingName, Price, Color, Brand, Size, Sex, Category, Description, ShippingAddress, Discount)
VALUES 
('Sweatshirt', 29.99, 'Gray', 'BrandA', 'M', 'Unisex', 'Tops', 'Warm and cozy sweatshirt', 'Warehouse1', 0.0),
('Shorts', 24.99, 'Green', 'BrandB', 'L', 'Men', 'Bottoms', 'Summer shorts', 'Warehouse2', 5.0),
('Skirt', 34.99, 'Pink', 'BrandC', 'S', 'Women', 'Bottoms', 'Stylish pink skirt', 'Warehouse3', 10.0),
('T-Shirt', 19.99, 'White', 'BrandD', 'M', 'Men', 'Tops', 'Casual white T-Shirt', 'Warehouse4', 2.0),
('Jeans', 49.99, 'Blue', 'BrandE', 'L', 'Unisex', 'Bottoms', 'Durable blue jeans', 'Warehouse5', 0.0),
('Jacket', 59.99, 'Black', 'BrandF', 'M', 'Men', 'Outerwear', 'Stylish black jacket', 'Warehouse6', 15.0),
('Blouse', 39.99, 'Yellow', 'BrandG', 'S', 'Women', 'Tops', 'Elegant yellow blouse', 'Warehouse7', 5.0),
('Sneakers', 69.99, 'Red', 'BrandH', '10', 'Unisex', 'Footwear', 'Comfortable red sneakers', 'Warehouse8', 0.0),
('Hat', 14.99, 'Brown', 'BrandI', 'M', 'Unisex', 'Accessories', 'Cool brown hat', 'Warehouse9', 5.0),
('Sunglasses', 89.99, 'Black', 'BrandJ', 'Free Size', 'Unisex', 'Accessories', 'Stylish black sunglasses', 'Warehouse10', 0.0),
('Belt', 29.99, 'Black', 'BrandK', 'L', 'Men', 'Accessories', 'Durable black belt', 'Warehouse11', 10.0),
('Scarf', 19.99, 'Purple', 'BrandL', 'Free Size', 'Women', 'Accessories', 'Soft purple scarf', 'Warehouse12', 0.0),
('Boots', 99.99, 'Brown', 'BrandM', '8', 'Men', 'Footwear', 'Stylish brown boots', 'Warehouse13', 20.0),
('Gloves', 24.99, 'Gray', 'BrandN', 'M', 'Women', 'Accessories', 'Warm gray gloves', 'Warehouse14', 0.0),
('Watch', 199.99, 'Silver', 'BrandO', 'Free Size', 'Men', 'Accessories', 'Luxury silver watch', 'Warehouse15', 15.0),
('Backpack', 49.99, 'Blue', 'BrandP', 'Free Size', 'Unisex', 'Bags', 'Spacious blue backpack', 'Warehouse16', 0.0),
('Earrings', 14.99, 'Gold', 'BrandQ', 'Free Size', 'Women', 'Accessories', 'Beautiful gold earrings', 'Warehouse17', 0.0),
('Tie', 19.99, 'Red', 'BrandR', 'Free Size', 'Men', 'Accessories', 'Classic red tie', 'Warehouse18', 5.0),
('Sandals', 29.99, 'Beige', 'BrandS', '9', 'Women', 'Footwear', 'Comfortable beige sandals', 'Warehouse19', 0.0),
('Laptop Bag', 59.99, 'Black', 'BrandT', 'Free Size', 'Unisex', 'Bags', 'Durable laptop bag', 'Warehouse20', 10.0),
('Hoodie', 39.99, 'Navy', 'BrandU', 'M', 'Unisex', 'Tops', 'Cozy navy hoodie', 'Warehouse21', 0.0),
('Leggings', 24.99, 'Black', 'BrandV', 'S', 'Women', 'Bottoms', 'Stretchy black leggings', 'Warehouse22', 0.0),
('Bracelet', 29.99, 'Silver', 'BrandW', 'Free Size', 'Women', 'Accessories', 'Elegant silver bracelet', 'Warehouse23', 10.0),
('Socks', 9.99, 'White', 'BrandX', 'M', 'Unisex', 'Footwear', 'Soft white socks', 'Warehouse24', 0.0),
('Wallet', 34.99, 'Brown', 'BrandY', 'Free Size', 'Men', 'Accessories', 'Stylish brown wallet', 'Warehouse25', 5.0),
('Purse', 49.99, 'Black', 'BrandZ', 'Free Size', 'Women', 'Bags', 'Elegant black purse', 'Warehouse26', 0.0),
('Swim Trunks', 29.99, 'Blue', 'BrandAA', 'L', 'Men', 'Bottoms', 'Comfortable blue swim trunks', 'Warehouse27', 10.0),
('Bikini', 39.99, 'Red', 'BrandBB', 'S', 'Women', 'Swimwear', 'Stylish red bikini', 'Warehouse28', 0.0),
('Flip-flops', 14.99, 'Green', 'BrandCC', '10', 'Unisex', 'Footwear', 'Casual green flip-flops', 'Warehouse29', 5.0),
('Pajamas', 34.99, 'Gray', 'BrandDD', 'M', 'Unisex', 'Sleepwear', 'Comfortable gray pajamas', 'Warehouse30', 0.0);
